FROM python:3.8-slim-buster
ENV LANG="zh_CN.utf8" TZ=Asia/Shanghai
WORKDIR /docker_codes
COPY ./mirrors /mirrors
RUN cp /mirrors/sources.list /etc/apt/sources.list\
    apt-get update -y && \
    apt install -y language-pack-zh-hans &&\
    pip3 install -i https://pypi.douban.com/simple -r /mirrors/requirements.txt

